### PR TITLE
test(style): Complete test coverage for composeStyle.js

### PR DESCRIPTION
**Pull request by tvthatsme**
**What**:
Test coverage for composeStyle.js: 100% Stmts, 100% Branch, 100% Funcs, and 100% Lines coverage when running `yarn test --coverage`

**Why**:
Keep working towards full test coverage for this project.

**How**:
Added three unit tests for the `compose` method exposed in composeStyle.js file.

**Checklist**:

* [ ] Documentation
* [x] Tests
* [x] Ready to be merged 
* [ ] Added myself to contributors table

### CODE REVIEW

**Comment by stereobooster** [comment]
Thank you

**Comment by tvthatsme** [comment]
Yep! We just need to figure out how to get Travis to start building with the new snapshots now... Any other ideas?

**Comment by stereobooster** [comment]
There is https://github.com/facebook/jest/issues/5270, maybe the same as ours

**Comment by tvthatsme** [comment]
Hmm, good find! Seems pretty similar. I think for our case, though, the snapshot is written to file locally (or else I wouldn't have been able to commit it, right?).

**Comment by stereobooster** [comment]
Yes locally it is written. It is some issue with Jest inside travis, I can not reproduce it anywhere else

**Pull request merged**
