### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by stereobooster** [comment]
There are no tests yet, but ok

**Comment by DanielRuf** [comment]
> There are no tests yet, but ok

What exactly do yoi mean? Even installing dependencues can fail on specific Node.js versions.

And you already test on Travis CI.

**Comment by stereobooster** [comment]
> And you already test on Travis CI.

Travis is not a test coverage. I didn't write a single test. There is one generated by kcd-scripts (tool that I used to bootstrap this repository).

**Comment by DanielRuf** [comment]
> Travis is not a test coverage. I didn't write a single test. There is one generated by kcd-scripts (tool that I used to bootstrap this repository).

Sure, but Travis is also meant to make sure that the package can be installed / used on different platforms and environments like Node.js 8 and 10 ;-)

Because I saw a few projects which failed on 10 due to dependencies or code issues ;-)

**Comment by stereobooster** [comment]
ok, I see your point

**Pull request merged**
